run:
  go: '1.21'
  timeout: 10m
issues:
  fix: true
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gosec
        - exhaustruct
linters:
  enable-all: true
  disable:
    - dupword
    - gocyclo
    - paralleltest
    - testpackage
    - gofumpt
    - nlreturn
    - varnamelen
    - wsl
    - funlen
    - errcheck
    - unparam
    - gocognit
    - lll
    - nolintlint
    - godox
    - cyclop
    - wrapcheck
    - unused
    - ireturn
    - nilnil
    - makezero
    - nestif
    - gochecknoglobals
    - typecheck
    - dupl
    - exhaustive
    - forbidigo
    - depguard
    - inamedparam
    - musttag
    - unconvert
    - perfsprint
    - gochecknoinits
    - containedctx
    - asasalint
    - mnd
    - err113
    - deadcode # Deprecated
    - exhaustivestruct # Deprecated
    - golint # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - maligned # Deprecated
    - gomnd # Deprecated
    - nosnakecase # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - varcheck # Deprecated
linters-settings:
  staticcheck:
    checks: ["all", "-SA5008", "-SA1008"]
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  gocritic:
    disabled-checks:
      - singleCaseSwitch
      - dupArg
  interfacebloat:
    max: 100
