version: "2"
run:
  go: "1.24"
linters:
  default: all
  disable:
    - asasalint
    - containedctx
    - cyclop
    - depguard
    - dupl
    - dupword
    - err113
    - errcheck
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - iface
    - inamedparam
    - ireturn
    - lll
    - makezero
    - mnd
    - musttag
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - paralleltest
    - perfsprint
    - testpackage
    - unconvert
    - unparam
    - unused
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - maintidx
    - funcorder
    - testableexamples
    - noinlineerr
  settings:
    gocritic:
      disabled-checks:
        - singleCaseSwitch
        - dupArg
    gosec:
      excludes:
        - G101
        - G115
        - G401
        - G505
    govet:
      disable:
        - printf
    interfacebloat:
      max: 100
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    staticcheck:
      checks:
        - all
        - -SA1006
        - -SA1008
        - -SA5008
        - -QF1008
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustruct
          - goconst
          - gosec
          - forcetypeassert
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
