linters:
  enable-all: true
  disable:
    - deadcode
    - paralleltest
    - testpackage
    - gofumpt
    - nlreturn
    - varnamelen
    - wsl
    - funlen
    - errcheck
    - unparam
    - gocognit
    - lll
    - goerr113
    - nolintlint
    - godox
    - cyclop
    - wrapcheck
    - unused
    - varcheck
    - ireturn
    - nilnil
    - makezero
    - gomnd
    - nestif
    - maligned
    - gochecknoglobals
    - forbidigo
    - scopelint
    - gochecknoinits
    - interfacebloat
    - maintidx
    - revive
    - depguard
linters-settings:
  gocritic:
    disabled-checks:
      - singleCaseSwitch
