issues:
  fix: true
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gosec
linters:
  enable-all: true
  disable:
    - exhaustruct
    - deadcode
    - paralleltest
    - testpackage
    - gofumpt
    - nlreturn
    - varnamelen
    - wsl
    - funlen
    - errcheck
    - unparam
    - gocognit
    - lll
    - goerr113
    - nolintlint
    - godox
    - cyclop
    - wrapcheck
    - unused
    - varcheck
    - ireturn
    - nilnil
    - makezero
    - gomnd
    - nestif
    - gochecknoglobals
    - scopelint
    - typecheck
    - dupl
    - exhaustive
    - forbidigo
    - maligned
    - revive
    - depguard
    - inamedparam
    - interfacer
    - ifshort
    - structcheck
    - nosnakecase
    - exhaustivestruct
    - golint
    - musttag
    - unconvert
linters-settings:
  staticcheck:
    checks: ["all", "-SA5008", "-SA1008"]
