run:
  timeout: 10m
issues:
  fix: true
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gosec
linters:
  enable-all: true
  disable:
    - deadcode
    - paralleltest
    - testpackage
    - gofumpt
    - nlreturn
    - varnamelen
    - wsl
    - funlen
    - errcheck
    - unparam
    - gocognit
    - lll
    - goerr113
    - nolintlint
    - godox
    - cyclop
    - wrapcheck
    - unused
    - varcheck
    - ireturn
    - nilnil
    - makezero
    - gomnd
    - nestif
    - gochecknoglobals
    - scopelint
    - typecheck
    - dupl
    - exhaustive
    - forbidigo
    - maligned
    - depguard
    - inamedparam
    - interfacer
    - ifshort
    - structcheck
    - nosnakecase
    - exhaustivestruct
    - golint
    - musttag
    - unconvert
    - perfsprint
    - gochecknoinits
    - containedctx
linters-settings:
  staticcheck:
    checks: ["all", "-SA5008", "-SA1008"]
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  interfacebloat:
    max: 100
