#!/bin/bash
export GOPATH=`pwd`

########################################
# Get dependency packages
########################################

dependencies=(
)

go get -u "${dependencies[@]}"

########################################
# Get latest source codes
########################################

git pull

go_uecho_path="github.com/cybergarage/uecho-go/net/echonet"
go_uecho_dir="src/${go_uecho_path}"
if [ -d ${go_uecho_dir} ]; then
  pushd ${go_uecho_dir} && git pull && popd
else
  go get -u ${go_uecho_path}
fi
