#!/bin/bash
export GOPATH=`pwd`

git pull

go_uecho_path="github.com/cybergarage/uecho-go/net/uecho"
go_uecho_dir="src/${go_uecho_path}"
if [ -d ${go_uecho_dir} ]; then
  pushd ${go_uecho_dir} && git pull && popd
else
  go get -u ${go_uecho_path}
fi
