// Copyright (C) 2018 Satoshi Konno. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package echonet

func (db *StandardDatabase) initManufactures() {
	db.addManufacture(NewManufacture(0x00002F, "AIPHONE CO., LTD."))
	db.addManufacture(NewManufacture(0x00011A, "ACCESS CO.,LTD."))
	db.addManufacture(NewManufacture(0x00002C, "AFT CO.,LTD"))
	db.addManufacture(NewManufacture(0x000068, "AISIN CORPORATION"))
	db.addManufacture(NewManufacture(0x000079, "Anritsu Engineering Co.,Ltd,"))
	db.addManufacture(NewManufacture(0x00007F, "ANRITSU CUSTOMER SUPPORT CO., LTD."))
	db.addManufacture(NewManufacture(0x000110, "ASUKA SOLUTION COMPANY LIMITED"))
	db.addManufacture(NewManufacture(0x000096, "Azbil Corporation"))
	db.addManufacture(NewManufacture(0x0000FD, "Bellnix Co.,LTD"))
	db.addManufacture(NewManufacture(0x00006F, "BUFFALO INC."))
	db.addManufacture(NewManufacture(0x0000B6, "Bunka Shutter Co., Ltd"))
	db.addManufacture(NewManufacture(0x0000D2, "CHOFUKOSAN.Co.Ltd"))
	db.addManufacture(NewManufacture(0x000088, "CHOFU SEISAKUSHO CO.,LTD."))
	db.addManufacture(NewManufacture(0x0000D5, "Choshu Industry Co., Ltd."))
	db.addManufacture(NewManufacture(0x0000A3, "Chubu Electric Power Grid Co.,Inc."))
	db.addManufacture(NewManufacture(0x0000FB, "CICO CORPORATION"))
	db.addManufacture(NewManufacture(0x0000F8, "CIMX INITIATIVE INC."))
	db.addManufacture(NewManufacture(0x000123, "Contec Co., Ltd."))
	db.addManufacture(NewManufacture(0x000067, "CORONA CORPORATION"))
	db.addManufacture(NewManufacture(0x00009C, "Diamond Electric Mfg.Co.,Ltd."))
	db.addManufacture(NewManufacture(0x000080, "DIAMOND&ZEBRA ELECTRIC MFG.CO.,LTD."))
	db.addManufacture(NewManufacture(0x000119, "DAIHEN Corporation"))
	db.addManufacture(NewManufacture(0x000008, "DAIKIN INDUSTRIES,LTD."))
	db.addManufacture(NewManufacture(0x000015, "Daikin Systems&Solutions Laboratory Ltd."))
	db.addManufacture(NewManufacture(0x00004F, "Daiwa House Industry co.,Ltd"))
	db.addManufacture(NewManufacture(0x000103, "Data Technology Inc."))
	db.addManufacture(NewManufacture(0x0000E3, "DDL Co.,Ltd"))
	db.addManufacture(NewManufacture(0x0000AD, "Delta Electronics (Japan), Inc."))
	db.addManufacture(NewManufacture(0x0000BE, "DENKEN Co.,Ltd."))
	db.addManufacture(NewManufacture(0x0000F4, "DENSO AIRCOOL CORPORATION"))
	db.addManufacture(NewManufacture(0x00003C, "DENSO Corporation"))
	db.addManufacture(NewManufacture(0x000109, "DENSO Co.,LTD."))
	db.addManufacture(NewManufacture(0x00012B, "DENSO WAVE INCORPORATED"))
	db.addManufacture(NewManufacture(0x000113, "EBARA JITSUGYO POWER CO., LTD."))
	db.addManufacture(NewManufacture(0x000057, "ELIIYPower Co.,ltd"))
	db.addManufacture(NewManufacture(0x00012E, "Eneres Co.,Ltd."))
	db.addManufacture(NewManufacture(0x000041, "ENEGATE CO.,LTD."))
	db.addManufacture(NewManufacture(0x00010A, "ENERGY GAP CORPORATION"))
	db.addManufacture(NewManufacture(0x0000F3, "Energy Gateway, Inc"))
	db.addManufacture(NewManufacture(0x0000F2, "Energy Solutions Inc."))
	db.addManufacture(NewManufacture(0x000072, "Eneres Co.,Ltd."))
	db.addManufacture(NewManufacture(0x0000DD, "EneStone Corporation"))
	db.addManufacture(NewManufacture(0x000055, "FAMILYNET JAPAN CORPORATION"))
	db.addManufacture(NewManufacture(0x0000F6, "Field Logic Inc."))
	db.addManufacture(NewManufacture(0x00012F, "FORMOSA BIO AND ENERGY CORP JAPAN"))
	db.addManufacture(NewManufacture(0x0000CB, "Fuji Electric Co.,Ltd"))
	db.addManufacture(NewManufacture(0x0000FC, "FUJI INDUSTRIAL CO.,Ltd."))
	db.addManufacture(NewManufacture(0x000051, "Fuji IT Co.,Ltd."))
	db.addManufacture(NewManufacture(0x00008A, "FUJITSU GENERAL LIMITED"))
	db.addManufacture(NewManufacture(0x00004E, "FUJITSU LIMITED"))
	db.addManufacture(NewManufacture(0x000090, "Fujitsu Component Limited"))
	db.addManufacture(NewManufacture(0x0000DE, "FUJIFILM Business Innovation Japan Corp"))
	db.addManufacture(NewManufacture(0x000097, "Future Technology Laboratories, Inc."))
	db.addManufacture(NewManufacture(0x00009B, "GASTAR Co.,Ltd"))
	db.addManufacture(NewManufacture(0x00008F, "Glamo Inc."))
	db.addManufacture(NewManufacture(0x000129, "GoodWe Japan K.K"))
	db.addManufacture(NewManufacture(0x00009F, "GS Yuasa International Ltd"))
	db.addManufacture(NewManufacture(0x000122, "Hanwha Q CELLS Japan CO.,LTD."))
	db.addManufacture(NewManufacture(0x000001, "Hitachi, Ltd."))
	db.addManufacture(NewManufacture(0x000022, "Hitachi Global Life Solutions, Inc."))
	db.addManufacture(NewManufacture(0x000040, "Hitachi High-Tech Solutions Corporation"))
	db.addManufacture(NewManufacture(0x000044, "Hitachi Industrial Equipment Systems Co.,Ltd."))
	db.addManufacture(NewManufacture(0x0000CC, "Hitachi-Johnson Controls Air Conditioning,Inc."))
	db.addManufacture(NewManufacture(0x0000E5, "Hitachi Power Solutions Co.,Ltd."))
	db.addManufacture(NewManufacture(0x0000E6, "Hokkaido Electrical Safety Services Foundation"))
	db.addManufacture(NewManufacture(0x0000B8, "Hokkaido Electric Power Co.,Inc."))
	db.addManufacture(NewManufacture(0x0000BB, "Hokuriku Electric Power Transmission & Distribution Company"))
	db.addManufacture(NewManufacture(0x0000A1, "Honda R&D Co., Ltd."))
	db.addManufacture(NewManufacture(0x000115, "HUAWEI TECHNOLOGIES JAPAN K.K."))
	db.addManufacture(NewManufacture(0x0000AC, "IDEC COROPRATION"))
	db.addManufacture(NewManufacture(0x00004D, "INABA DENKI SANGYO CO.,LTD."))
	db.addManufacture(NewManufacture(0x000056, "iND Co.,Ltd"))
	db.addManufacture(NewManufacture(0x0000ED, "INFINI Co. LTD"))
	db.addManufacture(NewManufacture(0x0000F2, "INTEC Inc."))
	db.addManufacture(NewManufacture(0x0000B1, "Internet Initiative Japan Inc."))
	db.addManufacture(NewManufacture(0x000087, "I-O DATA DEVICE,INC."))
	db.addManufacture(NewManufacture(0x00006B, "ISB Corporation"))
	db.addManufacture(NewManufacture(0x00010F, "Iwatani Corporation"))
	db.addManufacture(NewManufacture(0x000081, "IWATSU ELECTRIC CO., LTD."))
	db.addManufacture(NewManufacture(0x0000C3, "Japan Electric Meters Inspection Corporation"))
	db.addManufacture(NewManufacture(0x0000F7, "JCity,Inc."))
	db.addManufacture(NewManufacture(0x0000CA, "JSP CO.,LTD."))
	db.addManufacture(NewManufacture(0x0000D7, "Kaga Electronics co.,ltd."))
	db.addManufacture(NewManufacture(0x000077, "Kanagawa Institute of Technology"))
	db.addManufacture(NewManufacture(0x000063, "Kawamura Electric Inc."))
	db.addManufacture(NewManufacture(0x0000F0, "KANEKA CORPORATION"))
	db.addManufacture(NewManufacture(0x00010B, "KITANIHON ELECTRIC CABLE CO.,LTD."))
	db.addManufacture(NewManufacture(0x0000E8, "KOIZUMI LIGHTING TECHNOLOGY CORP."))
	db.addManufacture(NewManufacture(0x00003B, "KYOCERA Corporation"))
	db.addManufacture(NewManufacture(0x00008C, "Kyuden Technosystems Corporation"))
	db.addManufacture(NewManufacture(0x0000BF, "KYUSHU ELECTRIC POWER TRANSMISSION AND DISTRIBUTION CO.,INC."))
	db.addManufacture(NewManufacture(0x0000F1, "Laplace Systems Co., Ltd."))
	db.addManufacture(NewManufacture(0x000125, "LiveSmart KK"))
	db.addManufacture(NewManufacture(0x000025, "LIXIL Corporation"))
	db.addManufacture(NewManufacture(0x0000E0, "Looop Inc"))
	db.addManufacture(NewManufacture(0x00010C, "MAX CO., LTD."))
	db.addManufacture(NewManufacture(0x000078, "Maxell, Ltd."))
	db.addManufacture(NewManufacture(0x000058, "Mediotec Corporation"))
	db.addManufacture(NewManufacture(0x000120, "Meisei electric co.,ltd."))
	db.addManufacture(NewManufacture(0x000083, "Melco Techno Yokohama Corporation"))
	db.addManufacture(NewManufacture(0x000006, "Mitsubishi Electric Corp."))
	db.addManufacture(NewManufacture(0x000034, "MITSUBISHI ELECTRIC ENGINEERING COMPANY LIMITED"))
	db.addManufacture(NewManufacture(0x000105, "Mitsubishi Electric Lighting Corporation"))
	db.addManufacture(NewManufacture(0x00012A, "Monochrome Inc."))
	db.addManufacture(NewManufacture(0x00011D, "mui Lab, Inc."))
	db.addManufacture(NewManufacture(0x0000D4, "Murata Manufacturing Co.,Ltd."))
	db.addManufacture(NewManufacture(0x0000B0, "NALTEC, Inc."))
	db.addManufacture(NewManufacture(0x000106, "Nature Inc."))
	db.addManufacture(NewManufacture(0x000009, "NEC Corp."))
	db.addManufacture(NewManufacture(0x000118, "NEC Magnus Communications, Ltd"))
	db.addManufacture(NewManufacture(0x000073, "NEC Platforms, Ltd."))
	db.addManufacture(NewManufacture(0x000091, "NEC Platforms, Ltd."))
	db.addManufacture(NewManufacture(0x0000E2, "NextDrive Inc."))
	db.addManufacture(NewManufacture(0x000104, "Next Energy & Resources Co., Ltd."))
	db.addManufacture(NewManufacture(0x0000B2, "NF Blossom Technologies, Inc."))
	db.addManufacture(NewManufacture(0x0000A5, "Nichibei Co., Ltd."))
	db.addManufacture(NewManufacture(0x00006C, "NICHICON CORPORATION"))
	db.addManufacture(NewManufacture(0x0000EB, "NICHICON (KAMEOKA) CORPORATION"))
	db.addManufacture(NewManufacture(0x000102, "NICHICON (KUSATSU) CORPORATION"))
	db.addManufacture(NewManufacture(0x000112, "NICHIEI INTEC CO., LTD"))
	db.addManufacture(NewManufacture(0x000071, "NIHON SANGYO CO.,LTD."))
	db.addManufacture(NewManufacture(0x0000DC, "NIHON TECHNO CO.,LTD."))
	db.addManufacture(NewManufacture(0x00008D, "NIPPON TELEGRAPH AND TELEPHONE CORPORATION"))
	db.addManufacture(NewManufacture(0x000047, "NIPPON TELEGRAPH AND TELEPHONE EAST CORPORATION"))
	db.addManufacture(NewManufacture(0x000086, "NIPPON TELEGRAPH AND TELEPHONE WEST CORPORATION"))
	db.addManufacture(NewManufacture(0x000036, "NISSIN SYSTEMS CO., LTD."))
	db.addManufacture(NewManufacture(0x0000B7, "Nitto Kogyo Corporation"))
	db.addManufacture(NewManufacture(0x000054, "NORITZ CORP."))
	db.addManufacture(NewManufacture(0x00007C, "NSW Inc."))
	db.addManufacture(NewManufacture(0x0000A0, "NTT Advanced Technology Corporation"))
	db.addManufacture(NewManufacture(0x000023, "NTT COMWARE CORPORATION"))
	db.addManufacture(NewManufacture(0x000061, "NTT DATA INTELLILINK CORPORATION"))
	db.addManufacture(NewManufacture(0x0000E9, "NTT Smile Energy Inc."))
	db.addManufacture(NewManufacture(0x0000F5, "ODELIC CO., LTD."))
	db.addManufacture(NewManufacture(0x000012, "Oi Electric Co., Ltd"))
	db.addManufacture(NewManufacture(0x00006A, "OKAYA & CO., LTD."))
	db.addManufacture(NewManufacture(0x000114, "OkayaKiden Co.,Ltd."))
	db.addManufacture(NewManufacture(0x000048, "Oki Electric Industry Co., Ltd."))
	db.addManufacture(NewManufacture(0x000064, "OMRON SOCIAL SOLUTIONS CO.,LTD."))
	db.addManufacture(NewManufacture(0x00012C, "Onamba Co., Ltd."))
	db.addManufacture(NewManufacture(0x0000D8, "OSAKI DATATECH CO.,LTD."))
	db.addManufacture(NewManufacture(0x000052, "OSAKI ELECTRIC CO.,LTD."))
	db.addManufacture(NewManufacture(0x000127, "Paloma Co.,Ltd."))
	db.addManufacture(NewManufacture(0x00000B, "Panasonic Holdings Corporation"))
	db.addManufacture(NewManufacture(0x0000DA, "Panasonic Commercial Equipment Systems Co.,Ltd."))
	db.addManufacture(NewManufacture(0x0000FE, "Panasonic Ecology Systems Co.,Ltd."))
	db.addManufacture(NewManufacture(0x0000FA, "Plat'Home Co."))
	db.addManufacture(NewManufacture(0x000082, "PURPOSE CO.,LTD."))
	db.addManufacture(NewManufacture(0x000059, "Rinnai Corporation"))
	db.addManufacture(NewManufacture(0x000128, "SAIKOH ENGINEERING Co.,Ltd."))
	db.addManufacture(NewManufacture(0x00011E, "SAKAIGAWA CO., LTD"))
	db.addManufacture(NewManufacture(0x00011C, "SANDEN RETAIL SYSTEMS CORPORATION"))
	db.addManufacture(NewManufacture(0x00010E, "SANIX INCORPORATED"))
	db.addManufacture(NewManufacture(0x0000BA, "SankyoTateyama, Inc."))
	db.addManufacture(NewManufacture(0x0000C5, "SANWA SHUTTER CORPORATION"))
	db.addManufacture(NewManufacture(0x000093, "SATORI ELECTRIC CO.,LTD."))
	db.addManufacture(NewManufacture(0x000107, "SEIKO ELECTRIC CO.,LTD."))
	db.addManufacture(NewManufacture(0x00003A, "SEKISUI HOUSE, LTD."))
	db.addManufacture(NewManufacture(0x000005, "Sharp Corp"))
	db.addManufacture(NewManufacture(0x0000AE, "SHIKOKU ELECTRIC POWER CO.,INC."))
	db.addManufacture(NewManufacture(0x00002E, "SHIKOKU INSTRUMENTATION CO.,LTD"))
	db.addManufacture(NewManufacture(0x0000CE, "SHINDENGEN ELECTRIC MANUFACTURING CO.LTD."))
	db.addManufacture(NewManufacture(0x00010D, "Shizen Energy Inc."))
	db.addManufacture(NewManufacture(0x0000A8, "Smart Power System. Co,. Ltd."))
	db.addManufacture(NewManufacture(0x0000DF, "SMA Japan K.K."))
	db.addManufacture(NewManufacture(0x000100, "Smart Solar Corporation"))
	db.addManufacture(NewManufacture(0x00007E, "SMK Corporation"))
	db.addManufacture(NewManufacture(0x0000E1, "SoftBank Corp."))
	db.addManufacture(NewManufacture(0x00011B, "SolaX Power Network Technology (Zhe jiang) Co. , Ltd."))
	db.addManufacture(NewManufacture(0x000060, "Sony Computer Science Laboratories, Inc."))
	db.addManufacture(NewManufacture(0x00006E, "Soundvision co.,ltd."))
	db.addManufacture(NewManufacture(0x000108, "SOUSEI Technology Inc."))
	db.addManufacture(NewManufacture(0x000116, "Sungrow Power Supply Co., Ltd."))
	db.addManufacture(NewManufacture(0x000101, "Sunpot Co., Ltd"))
	db.addManufacture(NewManufacture(0x0000DB, "Suntech Power Japan Corporation"))
	db.addManufacture(NewManufacture(0x00003D, "SUMITOMO ELECTRIC INDUSTRIES, LTD."))
	db.addManufacture(NewManufacture(0x00003E, "SUMITOMO ELECTRIC NETWORKS, INC."))
	db.addManufacture(NewManufacture(0x000085, "TAKAOKA TOKO CO.,LTD"))
	db.addManufacture(NewManufacture(0x0000AF, "Takara Standard Co.,Ltd"))
	db.addManufacture(NewManufacture(0x0000E4, "technoeye Inc."))
	db.addManufacture(NewManufacture(0x0000FF, "TEPCO Energy Partner, Inc."))
	db.addManufacture(NewManufacture(0x0000EE, "TESSERA TECHNOLOGY INC."))
	db.addManufacture(NewManufacture(0x0000B5, "The Chugoku Electric Power Co., Ltd"))
	db.addManufacture(NewManufacture(0x00009A, "The Kansai Electric Power Co., Inc."))
	db.addManufacture(NewManufacture(0x0000CD, "TOCLAS CORPORATION"))
	db.addManufacture(NewManufacture(0x000126, "Togami Electric Mfg.co.,Ltd."))
	db.addManufacture(NewManufacture(0x0000F9, "TOHO ELECTRONICS INC."))
	db.addManufacture(NewManufacture(0x0000C2, "Tohoku Electric Meter Industry Co.,Inc"))
	db.addManufacture(NewManufacture(0x0000BC, "TohokuElectric Power Network Company,Incorporated"))
	db.addManufacture(NewManufacture(0x000099, "Tokyo Electric Power Company Holdings, Inc."))
	db.addManufacture(NewManufacture(0x0000B3, "TOPPERS Project, Inc."))
	db.addManufacture(NewManufacture(0x000111, "Topre Corporation"))
	db.addManufacture(NewManufacture(0x000017, "TOSHIBA CARRIER CORPORATION"))
	db.addManufacture(NewManufacture(0x000016, "Toshiba Corp."))
	db.addManufacture(NewManufacture(0x000043, "TOSHIBA DEVELOPMENT & ENGINEERING CORPORATION"))
	db.addManufacture(NewManufacture(0x0000EC, "Toshiba Energy Systems & Solutions Corporation"))
	db.addManufacture(NewManufacture(0x0000D9, "Toshiba IT & Control Systems Corporation"))
	db.addManufacture(NewManufacture(0x000069, "Toshiba Lifestyle Products & Services Corporation"))
	db.addManufacture(NewManufacture(0x00001B, "TOSHIBA LIGHTING & TECHNOLOGY CORPORATION"))
	db.addManufacture(NewManufacture(0x000035, "Toshiba Toko Meter Systems Co.,Ltd."))
	db.addManufacture(NewManufacture(0x000050, "TOTO LTD."))
	db.addManufacture(NewManufacture(0x0000EF, "TOYOTA INDUSTRIES CORPORATION"))
	db.addManufacture(NewManufacture(0x000121, "TOYOTA MOTOR CORPORATION"))
	db.addManufacture(NewManufacture(0x00011F, "TOYOTA TSUSHO CORPORATION"))
	db.addManufacture(NewManufacture(0x00005D, "Tranceboot Co.,Ltd."))
	db.addManufacture(NewManufacture(0x000076, "TSP CO.,Ltd"))
	db.addManufacture(NewManufacture(0x0000D0, "TSUBAKIMOTO CHAIN CO."))
	db.addManufacture(NewManufacture(0x0000C1, "Tsuken Electric Ind Co., Ltd."))
	db.addManufacture(NewManufacture(0x000053, "Ubiquitous AI Corporation"))
	db.addManufacture(NewManufacture(0x000117, "WWB Corporation"))
	db.addManufacture(NewManufacture(0x000095, "Yamato Denki Co.,Ltd."))
	db.addManufacture(NewManufacture(0x00009E, "YASKAWA ELECTRIC CORPORATION"))
	db.addManufacture(NewManufacture(0x00007A, "ZUKEN ELMIC,INC."))
	db.addManufacture(NewManufacture(0x0000B4, "4R Energy Corporation"))
}
